# .github/workflows/ci-cd.yml
name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Run workflow on commits to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Set up Docker Buildx for multi-platform builds
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Build the Docker image and tag it for Docker Hub
    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/sample-python-app:latest .

    # Push the Docker image to Docker Hub
    - name: Push Docker image to Docker Hub
      run: docker push ${{ secrets.DOCKER_USERNAME }}/sample-python-app:latest

    # Run the Docker container locally (optional step for testing locally)
    - name: Run Docker container
      run: docker run -d -p 5000:5000 ${{ secrets.DOCKER_USERNAME }}/sample-python-app:latest
